### ISSUE TITLE
[Bug] Comment box should not be able to be manually resized

### ISSUE THREAD

**Issue by Travanoid** [MangaDex/Bugs#16]
### Reproduction steps

1. Navigate to any manga page
2. Click on the "Comments" tab
3. Grab and drag the handle on the bottom-right of the comment box

### Expected occurrence
There is no handle, and the comment box is a fixed size that expands vertically if the comment is long enough to warrant it
### Actual occurrence
The comment box can be dragged to any height/width
### Impact on users
The user may resize the comment box without realizing, and think it's ugly or bugged
### Tested on
Chrome Version 64.0.3282.119 (Official Build) (64-bit)
### Possible resolution
Lock the comment box size at the current default, and expand it vertically if and only if the user is entering a very long comment that requires the extra space
### Screenshot

![image](https://user-images.githubusercontent.com/28797307/35715876-0783c3a4-078a-11e8-8885-bd315d5a7147.png)

**Comment by Teasday** [comment]
This is perfectly normal and expected default browser behaviour, not a bug. I don't see how there's anything wrong with allowing a user to resize an input field to any size they're comfortable with.

At best we should disable horizontal resizing with `#comment { resize: vertical; }` or maybe by adding `max-width: 100%;` so that it won't go out of bounds, but disabling manual resizing altogether or expanding it programmatically based on the input is not a good idea.

**Comment by misteranonimous** [comment]
Added resize: vertical;
