### ISSUE TITLE
Mangadex allows upload for non-existing manga

### ISSUE THREAD

**Issue by andreScutieri** [MangaDex/Bugs#7]
### Issue

When accessing the upload page for a random number, the page loads and allows upload. Upload fails, but .zip archive reaches the server. Potential malicious archives can be sent to server that way.

### Expected behaviour

Non-existing manga should default to 404 when trying to access their upload pages.

**Comment by Teasday** [comment]
For the moment this is basically a non-issue, since an uploaded archive to a nonexisting manga simply gets discarded without processing.

I agree though there's a better way to do this from the client's perspective, for example by first sending the metadata and only then the data, as it ensures the large upload won't even have to begin if the server wouldn't accept it in the first place.

**Comment by misteranonimous** [comment]
Fix: Upload page will display error if a non-existent manga ID is entered in the URL.The backend will also reject the upload if an attempt is made to inject directly into the POST variable.
